language: php

php:
  - 7.3
  - 7.4
  - 8.0

sudo: false

env:
  matrix:
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit
