name: Compile and publish site

on: push

jobs:
  cleaver:
    name: Build Cleaver with Docker
    runs-on: ubuntu-latest
    container:
      image: aschmelyun/cleaver:latest
    steps:
      - name: Running composer install
        run: composer install
      - name: Running npm install
        run: npm install
      - name: Running npm run production
        run: npm run production
