name: Compile and publish site
on: push

jobs:
  cleaver:
    name: Compile site assets with Docker
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run build command with Docker container
        uses: addnab/docker-run-action@v3
        with: 
          image: aschmelyun/cleaver:latest
          options: -v ${{ github.workspace }}:/var/www
          run: |
            composer install
            npm install
            npm run production