name: Compile and publish site
on: push

jobs:
  compile:
    name: Compile site assets and deploy to server
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run Cleaver with Docker container
        uses: addnab/docker-run-action@v3
        with:
          image: aschmelyun/cleaver:latest
          options: -v ${{ github.workspace }}:/var/www
          run: |
            composer install
            npm install
            npm run production
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'placeholder'
      - name: Adding known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy compiled assets
        run: rsync -avz ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/aschmelyun-site.com/dist/